#!/bin/bash

PROJECT_NAME=tiforg
DOCKER_PROJECT_NAME="do1cloud-tiforg"
DOCKER_PROJECT_TAG="latest"
BRANCH_NAME=$1
WOKRSPACE_OUTPUT_PATH="$JENKINS_HOME/product/tyyhzx/$BRANCH_NAME/$PROJECT_NAME"
DOCKER_IMAGES_NAME="$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_TAG"
HARBOR_PATH=$HARBOR_DOMAIN/zwrz/$DOCKER_PROJECT_NAME

docker rmi $DOCKER_IMAGES_NAME
docker build -t $DOCKER_IMAGES_NAME .
docker save $DOCKER_IMAGES_NAME | xz > $PROJECT_NAME.tar.xz

if [ ! -d "$WOKRSPACE_OUTPUT_PATH" ]; then
    mkdir -p $WOKRSPACE_OUTPUT_PATH
fi

cp -f $PROJECT_NAME.tar.xz $WOKRSPACE_OUTPUT_PATH

docker login $HARBOR_DOMAIN -u $HARBOR_USERNMAE -p $HARBOR_PASSWORD
docker tag $DOCKER_PROJECT_NAME $HARBOR_PATH
docker push $HARBOR_PATH